config/routes.rb
Rails.application.routes.draw do

  # RailsAdmin Engine
  # @implemented
  
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  # Authentication
  # @implemented
  devise_for :users

  # Application
  # @implemented
  root to: 'home#index'
  resource  :newsletter, only: [:create]
  resource  :contact, only: [:create]

  # Dashboard
  # @implemented
  namespace :dashboard do
    get '', to: 'home#index'
  end

  # API
  # @implemented
  namespace :api, path: '', constraint: { subdomain: 'api' } do
    namespace :v1 do
      with_options only: :index do |list|
        list.resources :clients
        list.resources :members
        list.resources :partners
        list.resources :posts
        list.resources :services
        list.resources :technologies
      end
    end
  end
end

app/models/newsletter.rb
# utf-8
class Newsletter < ApplicationRecord

  scope :registered, -> { where(status: true) }
  scope :unsregistered, -> { where(status: false) }

  before_create :signup, if: :valid?

  def signup
    self.status = true
    self.token = SecureRandom.urlsafe_base64
    self.confirmed_at = Date.today
    Mailer.new(NewsletterMailer, :signup, :deliver_now)
  end

  def cancel
    self.status = false
    self.token = nil
    Mailer.new(NewsletterMailer, :cancel, :deliver_now)
  end

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  validates :email,
            presence: true,
            uniqueness: true,
            allow_blank: false,
            length: { minimum: 3, maximum: 245 }

  validates :token,
            uniqueness: true
end

app/views/newsletter/_form.html.erb
<%= form_for(@newsletter, {url: newsletter_path, method: 'POST'}) do |f| %>
  <div class="field">
    <div class="col-md-6">
      <%= f.label :name %>
      <div class='input-group'>
      <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
      <%= f.text_field :name, class: 'form-control', required: 'required',
      placeholder: 'Digite o nome', autocomplete: 'off' %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="col-md-6">
      <%= f.label :email %>
      <div class='input-group'>
      <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
      <%= f.email_field :email, class: 'form-control', required: 'required',
      placeholder: 'Digite o e-mail', autocomplete: 'off' %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="col-md-12">
      <%= f.submit nil, class: 'btn btn-primary btn-lg top' %>
    </div>
  </div>
<% end %>