config/routes.rb
Rails.application.routes.draw do

  # RailsAdmin Engine
  # @implemented
  
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  # Authentication
  # @implemented
  devise_for :users

  # Application
  # @implemented
  root to: 'home#index'
  resource  :newsletter, only: [:create]
  resource  :contact, only: [:create]

  # Dashboard
  # @implemented
  namespace :dashboard do
    get '', to: 'home#index'
  end

  # API
  # @implemented
  namespace :api, path: '', constraint: { subdomain: 'api' } do
    namespace :v1 do
      with_options only: :index do |list|
        list.resources :clients
        list.resources :members
        list.resources :partners
        list.resources :posts
        list.resources :services
        list.resources :technologies
      end
    end
  end
end

app/models/contact.rb
# utf-8
class Contact
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :phone, :email, :message

  # Initialize
  # @implemented
  def initialize(params: {})
    @name = params[:name]
    @phone = params[:phone]
    @email = params[:email]
    @message = params[:message]
  end

  # data should be persisted?
  # @implemented
  def persisted?
    false
  end

  def send_email
    Mailer.new(ContactMailer, :sended,   :deliver_now)
    Mailer.new(ContactMailer, :received, :deliver_now)
  end

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  validates :phone,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 15 }

  validates :email,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 245 }

  validates :message,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 800 }
end

app/views/contact/_form.html.erb
<%= form_for(@contact, {url: contact_url, method: 'POST'}) do |f| %>
    <div class="field">
        <div class="col-md-6">
           <%= f.label :name %>
           <div class='input-group'>
           <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
           <%= f.text_field :name, class: 'form-control', required: 'required',
           placeholder: 'Digite o nome', autocomplete: 'off' %>
           </div>
        </div>
    </div>
    <div class="field">
        <div class="col-md-6">
            <%= f.label :phone %>
            <div class='input-group'>
            <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
            <%= f.phone_field :phone, class: 'form-control', required: 'required',
            placeholder: 'Digite o telefone', autocomplete: 'off' %>
            </div>
        </div>
    </div>
    <div class="field">
        <div class="col-md-12">
            <%= f.label :email %>
            <div class='input-group'>
            <div class='input-group-addon'><i class='glyphicon glyphicon-search'></i></div>
            <%= f.email_field :email, class: 'form-control', required: 'required',
            placeholder: 'Digite o e-mail', autocomplete: 'off' %>
            </div>
        </div>
    </div>
    <div class="field">
        <div class="col-md-12">
            <%= f.label :message %>
            <%= f.text_area :message, class: 'form-control', required: 'required',
            placeholder: 'Escreva sua mensagem...', autocomplete: 'off' %>
        </div>
    </div>
    <div class="field">
        <div class="col-md-12">
            <%= f.submit nil, class: 'btn btn-primary btn-lg top' %>
        </div>
    </div>
<% end %>