config/routes.rb
Rails.application.routes.draw do

  # RailsAdmin Engine
  # @implemented
  
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  # Authentication
  # @implemented
  devise_for :users

  # Application
  # @implemented
  root to: 'home#index'
  resource  :newsletter, only: [:create]
  resource  :contact, only: [:create]

  # Dashboard
  # @implemented
  namespace :dashboard do
    get '', to: 'home#index'
  end

  # API
  # @implemented
  namespace :api, path: '', constraint: { subdomain: 'api' } do
    namespace :v1 do
      with_options only: :index do |list|
        list.resources :clients
        list.resources :members
        list.resources :partners
        list.resources :posts
        list.resources :services
        list.resources :technologies
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class='jumbotron'>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
         <div class="col-md-5">
            <ul class='list-unstyled'>
               <li><h2><strong>CODE7EVEN</strong></h2></li>
               <li><p>Código rápido e eficaz para seu neǵocio.</p></li>
               <li> <i class='glyphicon glyphicon-search'></i> <a>contato@code7even.com</a> |
                 <i class='glyphicon glyphicon-search'></i> (11) 97195-6599 </li>
            </ul><!-- list-unstyled -->
         </div><!-- col-md-2 -->
         <div class="col-md-2 col-md-offset-1">
           <ul class='list-unstyled'>
              <li><h4><i class='glyphicon glyphicon-search'></i> SITEMAP</h4></li>
              <li><%= link_to 'Empresa', '#about' %></li>
              <li><%= link_to 'Serviços', '#about' %></li>
              <li><%= link_to 'Equipe', '#about' %></li>
              <li><%= link_to 'Octa7', '#about' %></li>
              <li><%= link_to 'Code7labs', '#about' %></li>
              <li><%= link_to 'Contato', '#about' %></li>
           </ul><!-- list-unstyled -->
         </div><!-- col-md-2 -->
         <div class="col-md-2">
           <ul class='list-unstyled'>
             <li><h4><i class='glyphicon glyphicon-search'></i> LINKS UTEIS</h4></li>
             <li><%= link_to 'Deseja iniciar um novo projeto?', '' %></li>
             <li><%= link_to 'Deseja reciclar um projeto já existente?', '' %></li>
           </ul><!-- list-unstyled -->
         </div><!-- col-md-2 -->
         <div class="col-md-2">
           <ul class='list--unstyled'>
             <li><h4><i class='glyphicon glyphicon-search'></i> EXTRAS</h4></li>
             <li><%= link_to 'Termos de Uso', '' %></li>
             <li><%= link_to 'Facebook', '' %></li>
             <li><%= link_to 'Linkedin', '' %></li>
             <li><%= link_to 'Twitter', '' %></li>
           </ul><!-- list-unstyled -->
         </div><!-- col-md-2 -->
      </div><!-- col-md-12 -->
    </div><!-- row -->
  </div><!-- container -->
</footer><!-- footer -->

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'CODE7EVEN', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
           <li class='active'><%= link_to 'Home', '#home' %></li>
           <li><%= link_to 'Empresa',   '#about'    %></li>
           <li><%= link_to 'Serviços',  '#services' %></li>
           <li><%= link_to 'Contato',   '#contact'  %></li>
           <li><%= link_to 'Blog',      '#blog'     %></li>
           <% if current_user %>
           <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
           aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
           <ul class="dropdown-menu">
             <li><%= link_to 'Dashboard', dashboard_path %></li>
             <li role="separator" class="divider"></li>
             <li><%= link_to 'Log Out', destroy_user_session_path %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
  <head>
    <title>CODE7EVEN | <%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style><%= yield :css %></style>
    <script><%= yield :js %></script>
  </head>
  <body class="<%= controller.controller_name %>" data-spy='scroll'
    ng-controller='ApplicationController'>
    <%= yield %>
  </body>
</html>